version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "sam-jenkins-demo-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ct46h2jug1zd"
s3_prefix = "sam-jenkins-demo-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
